version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/" 
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "UTC"
      
    allow:
      - dependency-name: "twinproduction/gatus"
      
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "MAINT"
      include: "scope"